name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install deps
        run: npm i --include=dev
      - name: Compile
        run: npx hardhat compile
      - name: Run hardhat tests
        run: npx hardhat test
